package housingbilling;

import java.util.*;
import housing.facts.*;
import com.rameses.rules.common.*;
import java.math.*;

global RuleAction action;


#rule "set-current-account" 
#	when
#		CurrentDate( CYR: year, CMON: month )
#		BI: BillItem( year < CYR, MON: month, YR: year, AMT: amount  )
#	then	
#		Map m = new HashMap();
#		m.put( "billitem",  BI );
#		m.put( "currentyear",  CYR );
#		m.put( "currentmonth",  CMON );
#		action.execute( "calc-penalty", m, drools );
#end
#
#rule "set-prior-account" 
#	when
#		CurrentDate( CYR: year )
#		BI: BillItem( year == CYR, MON: month, YR: year, AMT: amount  )
#	then	
#		System.out.println( "CURRENT ACCOUNT year is " + YR + " month: " + MON + " amount: " + AMT  );
#end
